// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: comments.sql

package db

import (
	"context"
	"time"
)

const addComment = `-- name: AddComment :one
INSERT INTO comments (user_id, series_id, body)
VALUES ($1, $2, $3)
RETURNING id, user_id, series_id, body, created_at
`

type AddCommentParams struct {
	UserID   *int64
	SeriesID *int64
	Body     string
}

func (q *Queries) AddComment(ctx context.Context, arg AddCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, addComment, arg.UserID, arg.SeriesID, arg.Body)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SeriesID,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}

const getCommentsBySeries = `-- name: GetCommentsBySeries :many
SELECT c.id, u.username, c.body, c.created_at
FROM comments c
JOIN users u ON u.id = c.user_id
WHERE c.series_id = $1
ORDER BY c.created_at DESC
`

type GetCommentsBySeriesRow struct {
	ID        int64
	Username  string
	Body      string
	CreatedAt time.Time
}

func (q *Queries) GetCommentsBySeries(ctx context.Context, seriesID *int64) ([]GetCommentsBySeriesRow, error) {
	rows, err := q.db.Query(ctx, getCommentsBySeries, seriesID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCommentsBySeriesRow
	for rows.Next() {
		var i GetCommentsBySeriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Body,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
