// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: episodes.sql

package db

import (
	"context"
)

const createEpisode = `-- name: CreateEpisode :one
INSERT INTO episodes (series_id, title, tiktok_url, episode_num)
VALUES ($1, $2, $3, $4)
RETURNING id, series_id, title, tiktok_url, episode_num
`

type CreateEpisodeParams struct {
	SeriesID   *int64
	Title      *string
	TiktokUrl  string
	EpisodeNum *int32
}

func (q *Queries) CreateEpisode(ctx context.Context, arg CreateEpisodeParams) (Episode, error) {
	row := q.db.QueryRow(ctx, createEpisode,
		arg.SeriesID,
		arg.Title,
		arg.TiktokUrl,
		arg.EpisodeNum,
	)
	var i Episode
	err := row.Scan(
		&i.ID,
		&i.SeriesID,
		&i.Title,
		&i.TiktokUrl,
		&i.EpisodeNum,
	)
	return i, err
}

const deleteEpisode = `-- name: DeleteEpisode :one
DELETE FROM episodes WHERE id = $1
RETURNING id, series_id, title, tiktok_url, episode_num
`

func (q *Queries) DeleteEpisode(ctx context.Context, id int64) (Episode, error) {
	row := q.db.QueryRow(ctx, deleteEpisode, id)
	var i Episode
	err := row.Scan(
		&i.ID,
		&i.SeriesID,
		&i.Title,
		&i.TiktokUrl,
		&i.EpisodeNum,
	)
	return i, err
}

const getEpisodeByID = `-- name: GetEpisodeByID :one
SELECT id, series_id, title, tiktok_url, episode_num
FROM episodes
WHERE id = $1
`

func (q *Queries) GetEpisodeByID(ctx context.Context, id int64) (Episode, error) {
	row := q.db.QueryRow(ctx, getEpisodeByID, id)
	var i Episode
	err := row.Scan(
		&i.ID,
		&i.SeriesID,
		&i.Title,
		&i.TiktokUrl,
		&i.EpisodeNum,
	)
	return i, err
}

const getEpisodesBySeries = `-- name: GetEpisodesBySeries :many
SELECT id, series_id, title, tiktok_url, episode_num
FROM episodes
WHERE series_id = $1
ORDER BY episode_num
`

func (q *Queries) GetEpisodesBySeries(ctx context.Context, seriesID *int64) ([]Episode, error) {
	rows, err := q.db.Query(ctx, getEpisodesBySeries, seriesID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Episode
	for rows.Next() {
		var i Episode
		if err := rows.Scan(
			&i.ID,
			&i.SeriesID,
			&i.Title,
			&i.TiktokUrl,
			&i.EpisodeNum,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
