// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Category struct {
	ID   int64
	Name string
	Slug string
}

type Comment struct {
	ID        int64
	UserID    *int64
	SeriesID  *int64
	Body      string
	CreatedAt time.Time
}

type Episode struct {
	ID         int64
	SeriesID   *int64
	Title      *string
	TiktokUrl  string
	EpisodeNum *int32
}

type Rating struct {
	ID        int64
	UserID    *int64
	SeriesID  *int64
	Rating    pgtype.Numeric
	CreatedAt time.Time
}

type Series struct {
	ID          int64
	Title       string
	Description *string
	CategoryID  *int64
	CoverUrl    *string
}

type Session struct {
	ID        string
	UserID    *int64
	ExpiresAt time.Time
}

type User struct {
	ID           int64
	Username     string
	Email        string
	PasswordHash string
	CreatedAt    time.Time
}
