// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Category struct {
	ID   int64
	Name string
	Slug string
}

type Episode struct {
	ID         int64
	SeriesID   pgtype.Int8
	Title      pgtype.Text
	TiktokUrl  string
	EpisodeNum pgtype.Int4
}

type Series struct {
	ID          int64
	Title       string
	Description pgtype.Text
	CategoryID  pgtype.Int8
	CoverUrl    pgtype.Text
	Rating      pgtype.Numeric
}
