// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Category struct {
	ID   int64
	Name string
	Slug string
}

type Episode struct {
	ID         int64
	SeriesID   *int64
	Title      *string
	TiktokUrl  string
	EpisodeNum *int32
}

type Series struct {
	ID          int64
	Title       string
	Description *string
	CategoryID  *int64
	CoverUrl    *string
	Rating      pgtype.Numeric
}
