// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (name, slug)
VALUES ($1, $2)
RETURNING id, name, slug
`

type CreateCategoryParams struct {
	Name string
	Slug string
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory, arg.Name, arg.Slug)
	var i Category
	err := row.Scan(&i.ID, &i.Name, &i.Slug)
	return i, err
}

const createEpisode = `-- name: CreateEpisode :one
INSERT INTO episodes (series_id, title, tiktok_url, episode_num)
VALUES ($1, $2, $3, $4)
RETURNING id, series_id, title, tiktok_url, episode_num
`

type CreateEpisodeParams struct {
	SeriesID   pgtype.Int8
	Title      pgtype.Text
	TiktokUrl  string
	EpisodeNum pgtype.Int4
}

func (q *Queries) CreateEpisode(ctx context.Context, arg CreateEpisodeParams) (Episode, error) {
	row := q.db.QueryRow(ctx, createEpisode,
		arg.SeriesID,
		arg.Title,
		arg.TiktokUrl,
		arg.EpisodeNum,
	)
	var i Episode
	err := row.Scan(
		&i.ID,
		&i.SeriesID,
		&i.Title,
		&i.TiktokUrl,
		&i.EpisodeNum,
	)
	return i, err
}

const createSeries = `-- name: CreateSeries :one
INSERT INTO series (title, description, category_id, cover_url, rating)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, title, description, category_id, cover_url, rating
`

type CreateSeriesParams struct {
	Title       string
	Description pgtype.Text
	CategoryID  pgtype.Int8
	CoverUrl    pgtype.Text
	Rating      pgtype.Numeric
}

func (q *Queries) CreateSeries(ctx context.Context, arg CreateSeriesParams) (Series, error) {
	row := q.db.QueryRow(ctx, createSeries,
		arg.Title,
		arg.Description,
		arg.CategoryID,
		arg.CoverUrl,
		arg.Rating,
	)
	var i Series
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.CategoryID,
		&i.CoverUrl,
		&i.Rating,
	)
	return i, err
}

const getAllCategories = `-- name: GetAllCategories :many
SELECT id, name, slug FROM categories
`

func (q *Queries) GetAllCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.Query(ctx, getAllCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(&i.ID, &i.Name, &i.Slug); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCategoryBySlug = `-- name: GetCategoryBySlug :one
SELECT id, name, slug FROM categories
WHERE slug = $1
`

func (q *Queries) GetCategoryBySlug(ctx context.Context, slug string) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryBySlug, slug)
	var i Category
	err := row.Scan(&i.ID, &i.Name, &i.Slug)
	return i, err
}

const getEpisodesBySeries = `-- name: GetEpisodesBySeries :many
SELECT id, series_id, title, tiktok_url, episode_num
FROM episodes
WHERE series_id = $1
ORDER BY episode_num
`

func (q *Queries) GetEpisodesBySeries(ctx context.Context, seriesID pgtype.Int8) ([]Episode, error) {
	rows, err := q.db.Query(ctx, getEpisodesBySeries, seriesID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Episode
	for rows.Next() {
		var i Episode
		if err := rows.Scan(
			&i.ID,
			&i.SeriesID,
			&i.Title,
			&i.TiktokUrl,
			&i.EpisodeNum,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSeriesByCategory = `-- name: GetSeriesByCategory :many
SELECT id, title, description, cover_url, rating
FROM series
WHERE category_id = $1
`

type GetSeriesByCategoryRow struct {
	ID          int64
	Title       string
	Description pgtype.Text
	CoverUrl    pgtype.Text
	Rating      pgtype.Numeric
}

func (q *Queries) GetSeriesByCategory(ctx context.Context, categoryID pgtype.Int8) ([]GetSeriesByCategoryRow, error) {
	rows, err := q.db.Query(ctx, getSeriesByCategory, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSeriesByCategoryRow
	for rows.Next() {
		var i GetSeriesByCategoryRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.CoverUrl,
			&i.Rating,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSeriesByID = `-- name: GetSeriesByID :one
SELECT id, title, description, cover_url, rating
FROM series
WHERE id = $1
`

type GetSeriesByIDRow struct {
	ID          int64
	Title       string
	Description pgtype.Text
	CoverUrl    pgtype.Text
	Rating      pgtype.Numeric
}

func (q *Queries) GetSeriesByID(ctx context.Context, id int64) (GetSeriesByIDRow, error) {
	row := q.db.QueryRow(ctx, getSeriesByID, id)
	var i GetSeriesByIDRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.CoverUrl,
		&i.Rating,
	)
	return i, err
}

const searchSeries = `-- name: SearchSeries :many
SELECT id, title, description, cover_url, rating
FROM series
WHERE title ILIKE '%' || $1 || '%'
`

type SearchSeriesRow struct {
	ID          int64
	Title       string
	Description pgtype.Text
	CoverUrl    pgtype.Text
	Rating      pgtype.Numeric
}

func (q *Queries) SearchSeries(ctx context.Context, dollar_1 pgtype.Text) ([]SearchSeriesRow, error) {
	rows, err := q.db.Query(ctx, searchSeries, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchSeriesRow
	for rows.Next() {
		var i SearchSeriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.CoverUrl,
			&i.Rating,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
