// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateEpisode(ctx context.Context, arg CreateEpisodeParams) (Episode, error)
	CreateSeries(ctx context.Context, arg CreateSeriesParams) (Series, error)
	GetAllCategories(ctx context.Context) ([]Category, error)
	GetCategoryBySlug(ctx context.Context, slug string) (Category, error)
	GetEpisodesBySeries(ctx context.Context, seriesID *int64) ([]Episode, error)
	GetSeriesByCategory(ctx context.Context, categoryID *int64) ([]GetSeriesByCategoryRow, error)
	GetSeriesByID(ctx context.Context, id int64) (GetSeriesByIDRow, error)
	SearchSeries(ctx context.Context, dollar_1 *string) ([]SearchSeriesRow, error)
}

var _ Querier = (*Queries)(nil)
