// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	AddComment(ctx context.Context, arg AddCommentParams) (Comment, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateEpisode(ctx context.Context, arg CreateEpisodeParams) (Episode, error)
	CreateSeries(ctx context.Context, arg CreateSeriesParams) (Series, error)
	CreateSeriesWithUploader(ctx context.Context, arg CreateSeriesWithUploaderParams) (Series, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	DeleteEpisode(ctx context.Context, id int64) (Episode, error)
	DeleteSeries(ctx context.Context, id int64) (Series, error)
	DeleteSession(ctx context.Context, id string) error
	GetAllCategories(ctx context.Context) ([]Category, error)
	GetAverageRating(ctx context.Context, seriesID *int64) (float64, error)
	GetCategoryBySlug(ctx context.Context, slug string) (Category, error)
	GetCommentsBySeries(ctx context.Context, seriesID *int64) ([]GetCommentsBySeriesRow, error)
	GetEpisodeByID(ctx context.Context, id int64) (Episode, error)
	GetEpisodesBySeries(ctx context.Context, seriesID *int64) ([]Episode, error)
	GetSeriesByCategory(ctx context.Context, categoryID *int64) ([]GetSeriesByCategoryRow, error)
	GetSeriesByID(ctx context.Context, id int64) (GetSeriesByIDRow, error)
	GetSeriesByUser(ctx context.Context, uploadedBy *int64) ([]GetSeriesByUserRow, error)
	GetSession(ctx context.Context, id string) (Session, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUserByID(ctx context.Context, id int64) (GetUserByIDRow, error)
	GetUserByIDWithPassword(ctx context.Context, id int64) (GetUserByIDWithPasswordRow, error)
	GetWatchProgress(ctx context.Context, arg GetWatchProgressParams) (WatchProgress, error)
	GetWatchProgressBySeries(ctx context.Context, arg GetWatchProgressBySeriesParams) ([]WatchProgress, error)
	ListNewSeries(ctx context.Context, limit int32) ([]ListNewSeriesRow, error)
	ListPopularSeries(ctx context.Context, limit int32) ([]ListPopularSeriesRow, error)
	SearchSeries(ctx context.Context, dollar_1 *string) ([]SearchSeriesRow, error)
	UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error
	UpdateSeries(ctx context.Context, arg UpdateSeriesParams) (Series, error)
	UpdateUsername(ctx context.Context, arg UpdateUsernameParams) (UpdateUsernameRow, error)
	UpsertRating(ctx context.Context, arg UpsertRatingParams) (Rating, error)
	UpsertWatchProgress(ctx context.Context, arg UpsertWatchProgressParams) (WatchProgress, error)
}

var _ Querier = (*Queries)(nil)
