// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ratings.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAverageRating = `-- name: GetAverageRating :one
SELECT ROUND(AVG(score)::numeric, 1) as average
FROM ratings WHERE series_id = $1
`

func (q *Queries) GetAverageRating(ctx context.Context, seriesID *int64) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, getAverageRating, seriesID)
	var average pgtype.Numeric
	err := row.Scan(&average)
	return average, err
}

const upsertRating = `-- name: UpsertRating :one
INSERT INTO ratings (user_id, series_id, score)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, series_id)
DO UPDATE SET score = $3
RETURNING id, user_id, series_id, score, created_at
`

type UpsertRatingParams struct {
	UserID   *int64
	SeriesID *int64
	Score    *int32
}

func (q *Queries) UpsertRating(ctx context.Context, arg UpsertRatingParams) (Rating, error) {
	row := q.db.QueryRow(ctx, upsertRating, arg.UserID, arg.SeriesID, arg.Score)
	var i Rating
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SeriesID,
		&i.Score,
		&i.CreatedAt,
	)
	return i, err
}
