// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ratings.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAverageRating = `-- name: GetAverageRating :one
SELECT COALESCE(ROUND(AVG(rating)::numeric, 1), 0)::float as average
FROM ratings WHERE series_id = $1
`

func (q *Queries) GetAverageRating(ctx context.Context, seriesID *int64) (float64, error) {
	row := q.db.QueryRow(ctx, getAverageRating, seriesID)
	var average float64
	err := row.Scan(&average)
	return average, err
}

const upsertRating = `-- name: UpsertRating :one
INSERT INTO ratings (user_id, series_id, rating)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, series_id)
DO UPDATE SET rating = $3
RETURNING id, user_id, series_id, rating, created_at
`

type UpsertRatingParams struct {
	UserID   *int64
	SeriesID *int64
	Rating   pgtype.Numeric
}

func (q *Queries) UpsertRating(ctx context.Context, arg UpsertRatingParams) (Rating, error) {
	row := q.db.QueryRow(ctx, upsertRating, arg.UserID, arg.SeriesID, arg.Rating)
	var i Rating
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SeriesID,
		&i.Rating,
		&i.CreatedAt,
	)
	return i, err
}
