// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: series.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSeries = `-- name: CreateSeries :one
INSERT INTO series (title, description, category_id, cover_url, rating)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, title, description, category_id, cover_url, rating
`

type CreateSeriesParams struct {
	Title       string
	Description pgtype.Text
	CategoryID  pgtype.Int8
	CoverUrl    pgtype.Text
	Rating      pgtype.Numeric
}

func (q *Queries) CreateSeries(ctx context.Context, arg CreateSeriesParams) (Series, error) {
	row := q.db.QueryRow(ctx, createSeries,
		arg.Title,
		arg.Description,
		arg.CategoryID,
		arg.CoverUrl,
		arg.Rating,
	)
	var i Series
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.CategoryID,
		&i.CoverUrl,
		&i.Rating,
	)
	return i, err
}

const getSeriesByCategory = `-- name: GetSeriesByCategory :many
SELECT id, title, description, cover_url, rating
FROM series
WHERE category_id = $1
`

type GetSeriesByCategoryRow struct {
	ID          int64
	Title       string
	Description pgtype.Text
	CoverUrl    pgtype.Text
	Rating      pgtype.Numeric
}

func (q *Queries) GetSeriesByCategory(ctx context.Context, categoryID pgtype.Int8) ([]GetSeriesByCategoryRow, error) {
	rows, err := q.db.Query(ctx, getSeriesByCategory, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSeriesByCategoryRow
	for rows.Next() {
		var i GetSeriesByCategoryRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.CoverUrl,
			&i.Rating,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSeriesByID = `-- name: GetSeriesByID :one
SELECT id, title, description, cover_url, rating
FROM series
WHERE id = $1
`

type GetSeriesByIDRow struct {
	ID          int64
	Title       string
	Description pgtype.Text
	CoverUrl    pgtype.Text
	Rating      pgtype.Numeric
}

func (q *Queries) GetSeriesByID(ctx context.Context, id int64) (GetSeriesByIDRow, error) {
	row := q.db.QueryRow(ctx, getSeriesByID, id)
	var i GetSeriesByIDRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.CoverUrl,
		&i.Rating,
	)
	return i, err
}

const searchSeries = `-- name: SearchSeries :many
SELECT id, title, description, cover_url, rating
FROM series
WHERE title ILIKE '%' || $1 || '%'
`

type SearchSeriesRow struct {
	ID          int64
	Title       string
	Description pgtype.Text
	CoverUrl    pgtype.Text
	Rating      pgtype.Numeric
}

func (q *Queries) SearchSeries(ctx context.Context, dollar_1 pgtype.Text) ([]SearchSeriesRow, error) {
	rows, err := q.db.Query(ctx, searchSeries, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchSeriesRow
	for rows.Next() {
		var i SearchSeriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.CoverUrl,
			&i.Rating,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
