// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
	"time"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, email, password_hash)
VALUES ($1, $2, $3)
RETURNING id, username, email, created_at
`

type CreateUserParams struct {
	Username     string
	Email        string
	PasswordHash string
}

type CreateUserRow struct {
	ID        int64
	Username  string
	Email     string
	CreatedAt time.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Username, arg.Email, arg.PasswordHash)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, password_hash
FROM users WHERE email = $1
`

type GetUserByEmailRow struct {
	ID           int64
	Username     string
	Email        string
	PasswordHash string
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email
FROM users WHERE id = $1
`

type GetUserByIDRow struct {
	ID       int64
	Username string
	Email    string
}

func (q *Queries) GetUserByID(ctx context.Context, id int64) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(&i.ID, &i.Username, &i.Email)
	return i, err
}

const getUserByIDWithPassword = `-- name: GetUserByIDWithPassword :one
SELECT id, username, email, password_hash
FROM users WHERE id = $1
`

type GetUserByIDWithPasswordRow struct {
	ID           int64
	Username     string
	Email        string
	PasswordHash string
}

func (q *Queries) GetUserByIDWithPassword(ctx context.Context, id int64) (GetUserByIDWithPasswordRow, error) {
	row := q.db.QueryRow(ctx, getUserByIDWithPassword, id)
	var i GetUserByIDWithPasswordRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
	)
	return i, err
}

const updatePassword = `-- name: UpdatePassword :exec
UPDATE users SET password_hash = $2 WHERE id = $1
`

type UpdatePasswordParams struct {
	ID           int64
	PasswordHash string
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error {
	_, err := q.db.Exec(ctx, updatePassword, arg.ID, arg.PasswordHash)
	return err
}

const updateUsername = `-- name: UpdateUsername :one
UPDATE users SET username = $2 WHERE id = $1 RETURNING id, username, email
`

type UpdateUsernameParams struct {
	ID       int64
	Username string
}

type UpdateUsernameRow struct {
	ID       int64
	Username string
	Email    string
}

func (q *Queries) UpdateUsername(ctx context.Context, arg UpdateUsernameParams) (UpdateUsernameRow, error) {
	row := q.db.QueryRow(ctx, updateUsername, arg.ID, arg.Username)
	var i UpdateUsernameRow
	err := row.Scan(&i.ID, &i.Username, &i.Email)
	return i, err

const createUserWithVerificationToken = `-- name: CreateUserWithVerificationToken :one
INSERT INTO users (username, email, password_hash, verification_token)
VALUES ($1, $2, $3, $4)
RETURNING id, username, email, created_at
`

type CreateUserWithVerificationTokenParams struct {
	Username           string
	Email              string
	PasswordHash       string
	VerificationToken  *string
}

type CreateUserWithVerificationTokenRow struct {
	ID        int64
	Username  string
	Email     string
	CreatedAt time.Time
}

func (q *Queries) CreateUserWithVerificationToken(ctx context.Context, arg CreateUserWithVerificationTokenParams) (CreateUserWithVerificationTokenRow, error) {
	row := q.db.QueryRow(ctx, createUserWithVerificationToken, arg.Username, arg.Email, arg.PasswordHash, arg.VerificationToken)
	var i CreateUserWithVerificationTokenRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByVerificationToken = `-- name: GetUserByVerificationToken :one
SELECT id, username, email, email_verified
FROM users WHERE verification_token = $1
`

type GetUserByVerificationTokenRow struct {
	ID             int64
	Username       string
	Email          string
	EmailVerified  bool
}

func (q *Queries) GetUserByVerificationToken(ctx context.Context, verificationToken string) (GetUserByVerificationTokenRow, error) {
	row := q.db.QueryRow(ctx, getUserByVerificationToken, verificationToken)
	var i GetUserByVerificationTokenRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.EmailVerified,
	)
	return i, err
}

const verifyEmail = `-- name: VerifyEmail :exec
UPDATE users SET email_verified = true, verification_token = NULL
WHERE verification_token = $1
`

func (q *Queries) VerifyEmail(ctx context.Context, verificationToken string) error {
	_, err := q.db.Exec(ctx, verifyEmail, verificationToken)
	return err
}

const getUserEmailVerified = `-- name: GetUserEmailVerified :one
SELECT email_verified FROM users WHERE id = $1
`

func (q *Queries) GetUserEmailVerified(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRow(ctx, getUserEmailVerified, id)
	var email_verified bool
	err := row.Scan(&email_verified)
	return email_verified, err
}

}