// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: watch_progress.sql

package db

import (
	"context"
)

const getWatchProgress = `-- name: GetWatchProgress :one
SELECT user_id, episode_id, progress_seconds, duration_seconds, completed, updated_at FROM watch_progress
WHERE user_id = $1 AND episode_id = $2
`

type GetWatchProgressParams struct {
	UserID    int64
	EpisodeID int64
}

func (q *Queries) GetWatchProgress(ctx context.Context, arg GetWatchProgressParams) (WatchProgress, error) {
	row := q.db.QueryRow(ctx, getWatchProgress, arg.UserID, arg.EpisodeID)
	var i WatchProgress
	err := row.Scan(
		&i.UserID,
		&i.EpisodeID,
		&i.ProgressSeconds,
		&i.DurationSeconds,
		&i.Completed,
		&i.UpdatedAt,
	)
	return i, err
}

const getWatchProgressBySeries = `-- name: GetWatchProgressBySeries :many
SELECT wp.user_id, wp.episode_id, wp.progress_seconds, wp.duration_seconds, wp.completed, wp.updated_at FROM watch_progress wp
JOIN episodes e ON e.id = wp.episode_id
WHERE wp.user_id = $1 AND e.series_id = $2
ORDER BY e.episode_num
`

type GetWatchProgressBySeriesParams struct {
	UserID   int64
	SeriesID *int64
}

func (q *Queries) GetWatchProgressBySeries(ctx context.Context, arg GetWatchProgressBySeriesParams) ([]WatchProgress, error) {
	rows, err := q.db.Query(ctx, getWatchProgressBySeries, arg.UserID, arg.SeriesID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WatchProgress
	for rows.Next() {
		var i WatchProgress
		if err := rows.Scan(
			&i.UserID,
			&i.EpisodeID,
			&i.ProgressSeconds,
			&i.DurationSeconds,
			&i.Completed,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertWatchProgress = `-- name: UpsertWatchProgress :one
INSERT INTO watch_progress (user_id, episode_id, progress_seconds, duration_seconds, completed, updated_at)
VALUES ($1, $2, $3, $4, $5, now())
ON CONFLICT (user_id, episode_id)
DO UPDATE SET
    progress_seconds = $3,
    duration_seconds = $4,
    completed = $5,
    updated_at = now()
RETURNING user_id, episode_id, progress_seconds, duration_seconds, completed, updated_at
`

type UpsertWatchProgressParams struct {
	UserID          int64
	EpisodeID       int64
	ProgressSeconds float64
	DurationSeconds float64
	Completed       bool
}

func (q *Queries) UpsertWatchProgress(ctx context.Context, arg UpsertWatchProgressParams) (WatchProgress, error) {
	row := q.db.QueryRow(ctx, upsertWatchProgress,
		arg.UserID,
		arg.EpisodeID,
		arg.ProgressSeconds,
		arg.DurationSeconds,
		arg.Completed,
	)
	var i WatchProgress
	err := row.Scan(
		&i.UserID,
		&i.EpisodeID,
		&i.ProgressSeconds,
		&i.DurationSeconds,
		&i.Completed,
		&i.UpdatedAt,
	)
	return i, err
}
